---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clink-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clink.dev
  resources:
  - clinkclusters
  - clinkjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clink.dev
  resources:
  - clinkclusters/finalizers
  - clinkjobs/finalizers
  verbs:
  - update
- apiGroups:
  - clink.dev
  resources:
  - clinkclusters/status
  - clinkjobs/status
  verbs:
  - get
  - patch
  - update
