// The capability-coverage gate: an impl compiled into this build either
// declares connector capability records or is explicitly exempted here with
// a reason.
//
// Before this existed the manifest was honest but tiny: three impls
// declared records and NINETEEN registered factories with none, so
// `clink --capabilities` under-reported the binary and the delivery
// analyser degraded to unknown for most of the catalogue. The gate makes
// the coverage mechanical: the enabled-impl list is GENERATED by
// impls/CMakeLists.txt from the same loop that links the aggregator, so a
// new `add_subdirectory` reaches this test without anyone remembering to
// update a second list, and the test fails until the new impl either
// declares records (the expectation map below) or states why it has none
// (the exempt map below). Both maps are maintained by hand ON PURPOSE - the
// point of the gate is that a human states the classification.

#include <cstdio>
#include <iostream>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "clink/connectors/capability.hpp"
#include "clink/plugin/install_defaults.hpp"
#include "clink/plugin/plugin.hpp"

#include "clink_enabled_impls.hpp"

namespace {

std::vector<std::string> split_csv(const std::string& s) {
    std::vector<std::string> out;
    std::stringstream ss(s);
    std::string item;
    while (std::getline(ss, item, ',')) {
        if (!item.empty()) {
            out.push_back(item);
        }
    }
    return out;
}

// Impls that are NOT connectors: nothing to declare, and the reason is the
// contract. Removing an entry (or adding an impl that is in neither map)
// fails the gate until a human classifies it.
const std::map<std::string, std::string> kExempt = {
    {"avro", "codec templates only; install() registers no factories"},
    {"rocksdb", "state backend, not a connector"},
    {"rocksdb_s3", "state backend composition, not a connector"},
    {"forst", "state backend, not a connector"},
    {"forst_s3", "state backend composition, not a connector"},
    {"tls", "transport layer for other connectors, not a connector"},
    {"etcd", "HA leader-election backend, not a connector"},
    {"wasm", "UDF language provider, not a connector"},
    {"onnx", "ML_PREDICT inference provider, not a connector"},
    {"vector_search", "VECTOR_SEARCH function provider, not a connector"},
};

// The records each connector impl is expected to declare. The names are
// user-visible connector identities (what `clink --capabilities` prints and
// the SQL `connector=` option matches), so one impl can carry several.
const std::map<std::string, std::vector<std::string>> kExpectedRecords = {
    {"kafka", {"kafka", "kafka_2pc"}},
    {"postgres", {"postgres", "postgres_2pc", "postgres_upsert"}},
    {"s3", {"s3", "s3_2pc"}},
    {"clickhouse", {"clickhouse"}},
    {"aws", {"kinesis", "firehose", "dynamodb"}},
    {"http_connector",
     {"http", "elasticsearch", "opensearch", "influxdb", "prometheus", "splunk_hec", "pubsub"}},
    {"redis", {"redis", "redis_upsert"}},
    {"mysql", {"mysql", "mysql_upsert"}},
    {"mqtt", {"mqtt"}},
    {"mongodb", {"mongo"}},
    {"iceberg", {"iceberg"}},
    {"rabbitmq", {"rabbitmq"}},
    {"nats", {"nats"}},
    {"pulsar", {"pulsar"}},
    {"cassandra", {"cassandra", "cassandra_upsert"}},
    {"gcs", {"gcs_parquet", "gcs_parquet_2pc"}},
    {"azure", {"azure_parquet", "azure_parquet_2pc"}},
    {"webhdfs", {"webhdfs_parquet"}},
    {"websocket", {"websocket"}},
};

}  // namespace

TEST(ConnectorManifestGate, EveryEnabledImplDeclaresCapabilitiesOrIsExempt) {
    clink::plugin::PluginRegistry reg;
    // install_defaults seeds the built-in type registries and then runs
    // every compiled impl's install(), which is where declarations live.
    clink::plugin::install_defaults(reg);
    auto& caps = clink::connectors::CapabilityRegistry::instance();

    const auto enabled = split_csv(kClinkEnabledImpls);
    ASSERT_FALSE(enabled.empty()) << "the generated enabled-impls list is empty; the build is "
                                     "misconfigured or the generation broke";

    std::vector<std::string> failures;
    for (const auto& impl : enabled) {
        if (kExempt.count(impl) != 0) {
            continue;
        }
        const auto it = kExpectedRecords.find(impl);
        if (it == kExpectedRecords.end()) {
            failures.push_back(
                impl +
                ": enabled in this build but neither declares capability records (add it to "
                "kExpectedRecords with the record names its install() declares) nor is exempt "
                "(add it to kExempt with the reason it is not a connector)");
            continue;
        }
        for (const auto& record : it->second) {
            const auto* c = caps.find(record);
            if (c == nullptr) {
                failures.push_back(impl + ": expected capability record '" + record +
                                   "' was not declared by install()");
                continue;
            }
            for (const auto& problem : c->self_check()) {
                failures.push_back(impl + ": record '" + record + "' fails self_check: " + problem);
            }
        }
    }
    std::string joined;
    for (const auto& f : failures) {
        joined += "\n  - " + f;
    }
    EXPECT_TRUE(failures.empty()) << failures.size()
                                  << " capability-coverage failure(s):" << joined;
}

// The reverse direction: an expectation for an impl this build did not
// enable is stale (renamed or removed impl), and an exempt entry for a
// nonexistent impl likewise. Keeps the maps from rotting.
TEST(ConnectorManifestGate, TheMapsAreDisjointAndNotObviouslyStale) {
    // Disjoint: an impl cannot be both exempt and expected - that is a map
    // edit that went wrong.
    std::vector<std::string> failures;
    for (const auto& [impl, _] : kExpectedRecords) {
        if (kExempt.count(impl) != 0) {
            failures.push_back(impl + " appears in BOTH kExpectedRecords and kExempt");
        }
    }
    std::string joined;
    for (const auto& f : failures) {
        joined += "\n  - " + f;
    }
    EXPECT_TRUE(failures.empty()) << joined;

    // Entries naming impls this build did not enable are NOTES, not
    // failures: deps are AUTO, so a map entry for an impl that is merely
    // absent on this machine is expected and must not fail the gate.
    const auto enabled = split_csv(kClinkEnabledImpls);
    const std::set<std::string> enabled_set(enabled.begin(), enabled.end());
    for (const auto& [impl, _] : kExpectedRecords) {
        if (enabled_set.count(impl) == 0) {
            std::cout << "[manifest-gate] note: kExpectedRecords names '" << impl
                      << "', not enabled in this build\n";
        }
    }
    for (const auto& [impl, _] : kExempt) {
        if (enabled_set.count(impl) == 0) {
            std::cout << "[manifest-gate] note: kExempt names '" << impl
                      << "', not enabled in this build\n";
        }
    }
}

#ifdef CLINK_CLI_BINARY
// The same coverage, through the front door. `clink --capabilities` rendered
// the registry before any impl's install() had run, so it listed the six
// built-ins and told the reader that every other connector "was not compiled
// in" - Kafka and ClickHouse included, in a binary that carried both. The
// published image's manifest, recorded as campaign evidence by
// qualification/infra/pull-image.sh, under-reported the same way.
TEST(ConnectorManifestGate, TheCliManifestCoversEveryEnabledImpl) {
    const std::string cmd = std::string{CLINK_CLI_BINARY} + " --capabilities-json";
    FILE* pipe = ::popen(cmd.c_str(), "r");
    ASSERT_NE(pipe, nullptr) << "could not run " << cmd;
    std::string out;
    char buf[4096];
    std::size_t n = 0;
    while ((n = std::fread(buf, 1, sizeof buf, pipe)) > 0) {
        out.append(buf, n);
    }
    ASSERT_EQ(::pclose(pipe), 0) << cmd << " failed; output:\n" << out;

    std::vector<std::string> failures;
    for (const auto& impl : split_csv(kClinkEnabledImpls)) {
        if (kExempt.count(impl) != 0) {
            continue;
        }
        const auto it = kExpectedRecords.find(impl);
        if (it == kExpectedRecords.end()) {
            continue;  // the registry gate above reports the unclassified impl
        }
        for (const auto& record : it->second) {
            if (out.find("\"name\":\"" + record + "\"") == std::string::npos) {
                failures.push_back(impl + ": record '" + record +
                                   "' is declared by install() but absent from the CLI manifest");
            }
        }
    }
    std::string joined;
    for (const auto& f : failures) {
        joined += "\n  - " + f;
    }
    EXPECT_TRUE(failures.empty()) << failures.size() << " manifest omission(s):" << joined;
}
#endif
