#!/usr/bin/env python3
"""QUAL-06's DAG generator: a seeded, deterministic SQL script whose compiled
job graph has a KNOWN width, and whose output is exactly verifiable by the
QUAL-05 oracle.

The shape: B branches, each reading the SAME topic through ITS OWN table
with ITS OWN consumer group, filtering to its k%B slice, all re-merged by
UNION ALL into one keyed COUNT(*) GROUP BY k under a declared state_ttl.

Two decisions here are correctness, not style:

  * ONE TABLE PER BRANCH, DISTINCT group_id. The planner replicates a
    scanned table's source per branch, and replicated scans of one table
    share its consumer group - the group then SPLITS partitions between
    the branch sources, each event reaches an arbitrary branch, and that
    branch's filter drops it unless it happens to match: ~(B-1)/B of the
    stream silently lost by construction. Distinct groups mean each branch
    reads the FULL topic and keeps its slice, so the union is an exact
    partition of the stream. The stated premise: B-fold broker read
    amplification.
  * The branch predicate partitions the key space (k % B == b), so
    SUM(n) over the settled sink equals events produced EXACTLY, and every
    key's n is recomputable from detspec - the QUAL-05 endstate oracle
    applies verbatim.

Width arithmetic (pinned by test_dag_gen.py against the real planner):
each branch plans to source + json decode + assigner + filter + project,
the union tree adds B-1 binary nodes, and the tail is keyer + aggregate +
json + sink, plus the planner's sink-boundary bind (item 78): deployed ops = 6B + 4.
"""
import argparse
import sys

TABLE_TMPL = """CREATE TABLE q6_in_{b} (event_id TEXT, k BIGINT, amount BIGINT, ts BIGINT)
  WITH (connector='kafka', format='json', brokers='__BROKERS__',
        topic='qual06-in', group_id='qual06-{run}-b{b}',
        auto_offset_reset='earliest',
        event_time_column='ts', watermark_lag_ms='__WM_LAG_MS__',
        state_ttl='__STATE_TTL_MS__', state_ttl_domain='event_time');
"""

SINK_TMPL = """CREATE TABLE q6_out (k BIGINT, n BIGINT)
  WITH (connector='postgres',
        conninfo='__CONNINFO__',
        "table"='public.q6_out',
        mode='upsert',
        primary_key='k');
"""


def generate(branches: int, run_tag: str) -> str:
    if branches < 2:
        raise SystemExit("dag-gen: need at least 2 branches")
    parts = [f"-- QUAL-06 generated pipeline: {branches} branches "
             f"(expected compiled width: {6 * branches + 4} operators).\n"
             "-- Generated by dag-gen.py; do not edit by hand.\n"]
    for b in range(branches):
        parts.append(TABLE_TMPL.format(b=b, run=run_tag))
    parts.append(SINK_TMPL)
    selects = [
        f"SELECT k, amount FROM q6_in_{b} WHERE (k % {branches}) = {b}"
        for b in range(branches)
    ]
    union = "\n  UNION ALL ".join(selects)
    parts.append(
        "-- Aliased projection: name-resolved sinks write NULL for unaliased\n"
        "-- expressions (the QUAL-04 silent-NULL trap).\n"
        f"INSERT INTO q6_out\nSELECT k, COUNT(*) AS n FROM (\n  {union}\n) u GROUP BY k;\n"
    )
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--branches", type=int, required=True)
    ap.add_argument("--run-tag", required=True,
                    help="uniquifies consumer groups per run (stale groups on a "
                         "recreated topic caused QUAL-05 diagnosis grief)")
    args = ap.parse_args()
    sys.stdout.write(generate(args.branches, args.run_tag))
    return 0


if __name__ == "__main__":
    sys.exit(main())
