// The local ONNX Runtime model provider against tiny in-tree fixture models: a float
// add, an int64+float named-output argmax, a string identity, and a multi-input add.
// The fixture bytes are generated by gen_model.py (this directory) and embedded in
// onnx_test_model.hpp so the test needs no external model file or Python at build time.

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <map>
#include <string>

#include <gtest/gtest.h>

#include "clink/config/json.hpp"
#include "clink/onnx/install.hpp"
#include "clink/onnx/onnx_model_provider.hpp"
#include "clink/plugin/plugin.hpp"
#include "clink/sql/model_provider.hpp"
#include "clink/sql/row.hpp"

#include "onnx_test_model.hpp"

namespace clink::onnx {
namespace {

// Write embedded model bytes to a uniquely-named temp .onnx and return its path.
std::filesystem::path write_model(const unsigned char* bytes, std::size_t len, const char* fname) {
    const auto path = std::filesystem::temp_directory_path() / fname;
    std::ofstream f(path, std::ios::binary | std::ios::trunc);
    f.write(reinterpret_cast<const char*>(bytes), static_cast<std::streamsize>(len));
    f.close();
    return path;
}

std::filesystem::path write_fixture_model() {
    return write_model(test::kOnnxAddModel, test::kOnnxAddModelLen, "clink_onnx_add_model.onnx");
}

TEST(OnnxModelProvider, RunsAddModelAndFillsOutputColumns) {
    const auto model = write_fixture_model();
    std::map<std::string, std::string> opts{
        {"model_path", model.string()},
        {"feature_columns", "f0,f1"},
        {"output_columns", "o0,o1"},
    };
    auto provider = make_onnx_model_provider(opts);
    ASSERT_NE(provider, nullptr);
    EXPECT_EQ(provider->name(), "onnx");

    clink::sql::Row in;
    in.values["f0"] = clink::config::JsonValue{1.0};
    in.values["f1"] = clink::config::JsonValue{2.0};
    const clink::sql::Row out = provider->predict(in);

    // y = x + [10, 20] -> o0 = 1 + 10 = 11, o1 = 2 + 20 = 22.
    ASSERT_TRUE(out.values.count("o0"));
    ASSERT_TRUE(out.values.count("o1"));
    EXPECT_DOUBLE_EQ(out.values.at("o0").as_number(), 11.0);
    EXPECT_DOUBLE_EQ(out.values.at("o1").as_number(), 22.0);

    std::filesystem::remove(model);
}

TEST(OnnxModelProvider, CoercesNumericStringFeatures) {
    const auto model = write_fixture_model();
    auto provider = make_onnx_model_provider({{"model_path", model.string()},
                                              {"feature_columns", "f0,f1"},
                                              {"output_columns", "o0,o1"}});
    clink::sql::Row in;
    in.values["f0"] = clink::config::JsonValue{std::string{"3"}};
    in.values["f1"] = clink::config::JsonValue{std::string{"4"}};
    const clink::sql::Row out = provider->predict(in);
    EXPECT_DOUBLE_EQ(out.values.at("o0").as_number(), 13.0);
    EXPECT_DOUBLE_EQ(out.values.at("o1").as_number(), 24.0);
    std::filesystem::remove(model);
}

// install() registers the provider under the name the ml_predict_row operator resolves
// by, so a CREATE MODEL WITH (provider='onnx', ...) reaches this provider at run time.
TEST(OnnxModelProvider, InstallRegistersOnnxProvider) {
    clink::plugin::PluginRegistry reg;
    clink::onnx::install(reg);
    EXPECT_TRUE(clink::sql::ModelProviderRegistry::global().contains("onnx"));

    const auto model = write_fixture_model();
    auto provider =
        clink::sql::ModelProviderRegistry::global().create("onnx",
                                                           {{"model_path", model.string()},
                                                            {"feature_columns", "f0,f1"},
                                                            {"output_columns", "o0,o1"}});
    ASSERT_NE(provider, nullptr);
    clink::sql::Row in;
    in.values["f0"] = clink::config::JsonValue{5.0};
    in.values["f1"] = clink::config::JsonValue{6.0};
    const clink::sql::Row out = provider->predict(in);
    EXPECT_DOUBLE_EQ(out.values.at("o0").as_number(), 15.0);
    EXPECT_DOUBLE_EQ(out.values.at("o1").as_number(), 26.0);
    std::filesystem::remove(model);
}

TEST(OnnxModelProvider, MissingModelPathThrows) {
    EXPECT_THROW((void)make_onnx_model_provider({{"feature_columns", "f0"}}), std::runtime_error);
}

TEST(OnnxModelProvider, MissingFeatureColumnThrows) {
    const auto model = write_fixture_model();
    auto provider = make_onnx_model_provider({{"model_path", model.string()},
                                              {"feature_columns", "f0,f1"},
                                              {"output_columns", "o0,o1"}});
    clink::sql::Row in;
    in.values["f0"] = clink::config::JsonValue{1.0};  // f1 absent
    EXPECT_THROW((void)provider->predict(in), std::runtime_error);
    std::filesystem::remove(model);
}

// Named, mixed-dtype outputs read by column name: label is int64 (argmax), score is
// float32 (max). The 3 feature columns feed the single unnamed input x[1,3].
TEST(OnnxModelProvider, NamedMixedDtypeOutputs) {
    const auto model =
        write_model(test::kOnnxArgmaxModel, test::kOnnxArgmaxModelLen, "clink_onnx_argmax.onnx");
    auto provider = make_onnx_model_provider({{"model_path", model.string()},
                                              {"feature_columns", "f0,f1,f2"},
                                              {"output_columns", "label,score"}});
    clink::sql::Row in;
    in.values["f0"] = clink::config::JsonValue{0.1};
    in.values["f1"] = clink::config::JsonValue{0.9};  // the argmax
    in.values["f2"] = clink::config::JsonValue{0.2};
    const clink::sql::Row out = provider->predict(in);
    ASSERT_TRUE(out.values.count("label"));
    ASSERT_TRUE(out.values.count("score"));
    EXPECT_DOUBLE_EQ(out.values.at("label").as_number(), 1.0);  // int64 argmax = index 1
    EXPECT_NEAR(out.values.at("score").as_number(), 0.9, 1e-6);
    std::filesystem::remove(model);
}

// A string input tensor and a string output tensor (Identity on a string).
TEST(OnnxModelProvider, StringInputAndOutput) {
    const auto model =
        write_model(test::kOnnxStrIdModel, test::kOnnxStrIdModelLen, "clink_onnx_strid.onnx");
    auto provider = make_onnx_model_provider(
        {{"model_path", model.string()}, {"feature_columns", "s"}, {"output_columns", "out"}});
    clink::sql::Row in;
    in.values["s"] = clink::config::JsonValue{std::string("hello world")};
    const clink::sql::Row out = provider->predict(in);
    ASSERT_TRUE(out.values.count("out"));
    EXPECT_EQ(out.values.at("out").as_string(), "hello world");
    std::filesystem::remove(model);
}

// Named multi-input: a and b are separate input tensors fed by same-named columns.
TEST(OnnxModelProvider, NamedMultiInput) {
    const auto model =
        write_model(test::kOnnxAdd2Model, test::kOnnxAdd2ModelLen, "clink_onnx_add2.onnx");
    auto provider = make_onnx_model_provider(
        {{"model_path", model.string()}, {"feature_columns", "a,b"}, {"output_columns", "sum"}});
    clink::sql::Row in;
    in.values["a"] = clink::config::JsonValue{3.0};
    in.values["b"] = clink::config::JsonValue{4.0};
    const clink::sql::Row out = provider->predict(in);
    ASSERT_TRUE(out.values.count("sum"));
    EXPECT_DOUBLE_EQ(out.values.at("sum").as_number(), 7.0);
    std::filesystem::remove(model);
}

}  // namespace
}  // namespace clink::onnx
