// The local ONNX Runtime model provider against a tiny in-tree model (y = x + [10,20],
// float32[1,2] -> float32[1,2]). The fixture bytes are generated by
// scratchpad/gen_model.py and embedded in onnx_test_model.hpp so the test needs no
// external model file or Python at build time.

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <map>
#include <string>

#include <gtest/gtest.h>

#include "clink/config/json.hpp"
#include "clink/onnx/install.hpp"
#include "clink/onnx/onnx_model_provider.hpp"
#include "clink/plugin/plugin.hpp"
#include "clink/sql/model_provider.hpp"
#include "clink/sql/row.hpp"

#include "onnx_test_model.hpp"

namespace clink::onnx {
namespace {

// Write the embedded model to a temp .onnx and return its path.
std::filesystem::path write_fixture_model() {
    const auto path = std::filesystem::temp_directory_path() / "clink_onnx_add_model.onnx";
    std::ofstream f(path, std::ios::binary | std::ios::trunc);
    f.write(reinterpret_cast<const char*>(test::kOnnxAddModel),
            static_cast<std::streamsize>(test::kOnnxAddModelLen));
    f.close();
    return path;
}

TEST(OnnxModelProvider, RunsAddModelAndFillsOutputColumns) {
    const auto model = write_fixture_model();
    std::map<std::string, std::string> opts{
        {"model_path", model.string()},
        {"feature_columns", "f0,f1"},
        {"output_columns", "o0,o1"},
    };
    auto provider = make_onnx_model_provider(opts);
    ASSERT_NE(provider, nullptr);
    EXPECT_EQ(provider->name(), "onnx");

    clink::sql::Row in;
    in.values["f0"] = clink::config::JsonValue{1.0};
    in.values["f1"] = clink::config::JsonValue{2.0};
    const clink::sql::Row out = provider->predict(in);

    // y = x + [10, 20] -> o0 = 1 + 10 = 11, o1 = 2 + 20 = 22.
    ASSERT_TRUE(out.values.count("o0"));
    ASSERT_TRUE(out.values.count("o1"));
    EXPECT_DOUBLE_EQ(out.values.at("o0").as_number(), 11.0);
    EXPECT_DOUBLE_EQ(out.values.at("o1").as_number(), 22.0);

    std::filesystem::remove(model);
}

TEST(OnnxModelProvider, CoercesNumericStringFeatures) {
    const auto model = write_fixture_model();
    auto provider = make_onnx_model_provider({{"model_path", model.string()},
                                              {"feature_columns", "f0,f1"},
                                              {"output_columns", "o0,o1"}});
    clink::sql::Row in;
    in.values["f0"] = clink::config::JsonValue{std::string{"3"}};
    in.values["f1"] = clink::config::JsonValue{std::string{"4"}};
    const clink::sql::Row out = provider->predict(in);
    EXPECT_DOUBLE_EQ(out.values.at("o0").as_number(), 13.0);
    EXPECT_DOUBLE_EQ(out.values.at("o1").as_number(), 24.0);
    std::filesystem::remove(model);
}

// install() registers the provider under the name the ml_predict_row operator resolves
// by, so a CREATE MODEL WITH (provider='onnx', ...) reaches this provider at run time.
TEST(OnnxModelProvider, InstallRegistersOnnxProvider) {
    clink::plugin::PluginRegistry reg;
    clink::onnx::install(reg);
    EXPECT_TRUE(clink::sql::ModelProviderRegistry::global().contains("onnx"));

    const auto model = write_fixture_model();
    auto provider =
        clink::sql::ModelProviderRegistry::global().create("onnx",
                                                           {{"model_path", model.string()},
                                                            {"feature_columns", "f0,f1"},
                                                            {"output_columns", "o0,o1"}});
    ASSERT_NE(provider, nullptr);
    clink::sql::Row in;
    in.values["f0"] = clink::config::JsonValue{5.0};
    in.values["f1"] = clink::config::JsonValue{6.0};
    const clink::sql::Row out = provider->predict(in);
    EXPECT_DOUBLE_EQ(out.values.at("o0").as_number(), 15.0);
    EXPECT_DOUBLE_EQ(out.values.at("o1").as_number(), 26.0);
    std::filesystem::remove(model);
}

TEST(OnnxModelProvider, MissingModelPathThrows) {
    EXPECT_THROW((void)make_onnx_model_provider({{"feature_columns", "f0"}}), std::runtime_error);
}

TEST(OnnxModelProvider, MissingFeatureColumnThrows) {
    const auto model = write_fixture_model();
    auto provider = make_onnx_model_provider({{"model_path", model.string()},
                                              {"feature_columns", "f0,f1"},
                                              {"output_columns", "o0,o1"}});
    clink::sql::Row in;
    in.values["f0"] = clink::config::JsonValue{1.0};  // f1 absent
    EXPECT_THROW((void)provider->predict(in), std::runtime_error);
    std::filesystem::remove(model);
}

}  // namespace
}  // namespace clink::onnx
