#!/usr/bin/env python3
"""Generate or verify the declared plugin-ABI surface manifest.

The manifest (scripts/plugin-abi-surface.txt) names the exact set of public
headers whose content is hashed into the plugin ABI fingerprint - the load
gate between a compiled plugin/job .so and a clink cluster. The declared
surface is the transitive #include closure of the plugin authoring entry
points: everything a plugin translation unit can legitimately reach, and
therefore everything whose layout, inline bodies or templates can cross the
dlopen boundary. Headers outside the surface (sql/, embed/, test/, ...) are
host-side features a plugin is never handed across the boundary; edits to
them no longer rotate the fingerprint or invalidate deployed plugins.

Entry points are every header under the authoring directories:

    include/clink/api/        the fluent pipeline surface
    include/clink/job/        CLINK_REGISTER_JOB
    include/clink/plugin/     the plugin handshake and registry
    include/clink/operators/  operator/source/sink base classes and helpers
    include/clink/connectors/ built-in connector headers jobs include directly

operators/ and connectors/ are included wholesale rather than by closure
because first-party jobs demonstrably include individual headers from them
(sink_operator.hpp, file_source.hpp, parquet_sink.hpp, ...). The *.hpp.in
templates under plugin/ stand in for their generated headers, which live in
the build tree and would otherwise be self-referential.

Two computed sections:

    [headers]  sorted repo-relative paths; CMake hashes exactly these files.
    [options]  CLINK_* tokens used in conditional compilation inside the
               surface. Each must map to a build option folded into the
               fingerprint material (CMakeLists.txt), so two builds that
               disagree on a layout-affecting option cannot exchange
               plugins. Impl-gating tokens (CLINK_HAS_KAFKA, ...) are
               excluded: they gate includes of per-impl headers that live
               under impls/*/include, outside the contract, and are set
               per-target rather than tree-wide.

Non-CLINK conditional tokens (e.g. ARROW_S3 in connector headers) are
deliberately not collected: they are decided by the pinned Arrow build,
which enters the material as arrow_version.

The script also cross-checks every first-party plugin source (any .cpp
containing CLINK_REGISTER_JOB / CLINK_REGISTER_PLUGIN / CLINK_DECLARE_PLUGIN)
against the manifest: a job that includes a clink header outside the declared
surface would be silent UB when that header changes, so it fails this check
instead.

Usage:
    scripts/gen-plugin-abi-surface.py           regenerate the manifest
    scripts/gen-plugin-abi-surface.py --check   verify it is current (CI,
                                                pre-commit); exit 1 on drift
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INCLUDE_ROOT = REPO_ROOT / "include"
IMPLS_ROOT = REPO_ROOT / "impls"
MANIFEST_PATH = REPO_ROOT / "scripts" / "plugin-abi-surface.txt"

ENTRY_DIRS = [
    "include/clink/api",
    "include/clink/connectors",
    "include/clink/job",
    "include/clink/operators",
    "include/clink/plugin",
]

# Exception types thrown across the dlopen boundary and caught BY TYPE on the
# host side (worker.cpp catches plugin-thrown CheckpointIntegrityError). Their
# layout crosses even though authoring code rarely includes them, so they are
# contract surface by construction; TransportOnlyFailure's header
# (plugin_impl.hpp) is already in the closure.
EXTRA_ENTRY_FILES = [
    "include/clink/state/checkpoint_integrity.hpp",
]

# Generated headers resolve in the build tree; their configure templates are
# the hashable stand-ins and are picked up by the plugin/ entry glob.
GENERATED_HEADERS = {
    "clink/plugin/abi_version.hpp": "include/clink/plugin/abi_version.hpp.in",
    "clink/plugin/abi_surface.hpp": "include/clink/plugin/abi_surface.hpp.in",
}

INCLUDE_RE = re.compile(r'^\s*#\s*include\s+["<](clink/[^">]+)[">]')
CONDITIONAL_RE = re.compile(r"^\s*#\s*(?:if|elif|ifdef|ifndef)\b(.*)$")
DEFINE_RE = re.compile(r"^\s*#\s*define\s+(CLINK_[A-Z0-9_]+)")
TOKEN_RE = re.compile(r"\bCLINK_[A-Z0-9_]+\b")
PLUGIN_MARKER_RE = re.compile(
    r"\bCLINK_(?:REGISTER_JOB|REGISTER_PLUGIN|DECLARE_PLUGIN)\s*\("
)

# Directories scanned for first-party plugin sources.
PLUGIN_SOURCE_ROOTS = [
    "examples",
    "benchmarks",
    "qualification",
    "tests",
    "docs/consumer-examples",
]

HEADER_COMMENT = """\
# Declared plugin-ABI surface. Generated by scripts/gen-plugin-abi-surface.py;
# do not edit by hand - regenerate instead. CMake hashes exactly the files in
# [headers] (plus the [options] values and the pinned Arrow version) into the
# plugin ABI fingerprint, the load gate between a compiled plugin .so and a
# cluster. A diff here IS a change to the extension compatibility contract and
# should be reviewed as one. See docs/design/010-stable-extension-model.md.
"""


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def is_impl_header(inc: str) -> bool:
    """True when `inc` (a clink/... include path) resolves under impls/*/include."""
    if not IMPLS_ROOT.is_dir():
        return False
    for impl_dir in IMPLS_ROOT.iterdir():
        if (impl_dir / "include" / inc).is_file():
            return True
    return False


def collect_entry_files() -> list[Path]:
    files: list[Path] = []
    for d in ENTRY_DIRS:
        root = REPO_ROOT / d
        if not root.is_dir():
            sys.exit(f"error: entry directory missing: {d}")
        files.extend(sorted(root.rglob("*.hpp")))
        files.extend(sorted(root.rglob("*.hpp.in")))
    for f in EXTRA_ENTRY_FILES:
        path = REPO_ROOT / f
        if not path.is_file():
            sys.exit(f"error: entry file missing: {f}")
        files.append(path)
    return files


def compute_closure(entries: list[Path]) -> tuple[set[Path], list[str]]:
    """BFS the #include closure over include/clink. Returns (files, errors)."""
    surface: set[Path] = set(entries)
    queue = list(entries)
    errors: list[str] = []
    seen_includes: set[str] = set()
    while queue:
        f = queue.pop()
        for line in read_text(f).splitlines():
            m = INCLUDE_RE.match(line)
            if not m:
                continue
            inc = m.group(1)
            if inc in seen_includes:
                continue
            seen_includes.add(inc)
            if inc in GENERATED_HEADERS:
                tmpl = REPO_ROOT / GENERATED_HEADERS[inc]
                if tmpl.is_file():
                    if tmpl not in surface:
                        surface.add(tmpl)
                        queue.append(tmpl)
                else:
                    errors.append(
                        f"{f.relative_to(REPO_ROOT)}: generated header "
                        f"'{inc}' has no template at {GENERATED_HEADERS[inc]}"
                    )
                continue
            resolved = INCLUDE_ROOT / inc
            if resolved.is_file():
                if resolved not in surface:
                    surface.add(resolved)
                    queue.append(resolved)
            elif is_impl_header(inc):
                # Per-impl header under impls/*/include: outside the declared
                # contract (gated per-target by CLINK_HAS_<impl>).
                continue
            else:
                errors.append(
                    f"{f.relative_to(REPO_ROOT)}: unresolvable include "
                    f'"{inc}" (not under include/ or impls/*/include/)'
                )
    return surface, errors


def impl_gating_tokens() -> set[str]:
    """Tokens in install_defaults.hpp that gate an impl-header include."""
    path = INCLUDE_ROOT / "clink/plugin/install_defaults.hpp"
    tokens: set[str] = set()
    pending: str | None = None
    for line in read_text(path).splitlines():
        cond = CONDITIONAL_RE.match(line)
        if cond:
            found = TOKEN_RE.findall(cond.group(1))
            pending = found[0] if len(found) == 1 else None
            continue
        m = INCLUDE_RE.match(line)
        if m and pending and is_impl_header(m.group(1)):
            tokens.add(pending)
        if line.strip().startswith("#endif"):
            pending = None
    return tokens


def collect_option_tokens(surface: set[Path]) -> set[str]:
    excluded = impl_gating_tokens()
    tokens: set[str] = set()
    defined_in_surface: set[str] = set()
    for f in surface:
        for line in read_text(f).splitlines():
            define = DEFINE_RE.match(line)
            if define:
                defined_in_surface.add(define.group(1))
                continue
            cond = CONDITIONAL_RE.match(line)
            if not cond:
                continue
            tokens.update(TOKEN_RE.findall(cond.group(1)))
    # A token the surface #defines itself (helper macros such as
    # CLINK_ABI_HAS_FEATURE or CLINK_PLUGIN_TARGET_TRIPLE) is part of the
    # hashed header text, not a build option the two sides could disagree on.
    return tokens - excluded - defined_in_surface


def check_plugin_sources(surface: set[Path]) -> list[str]:
    """Every first-party plugin .cpp may only include declared-surface headers."""
    surface_incs = {
        str(p.relative_to(INCLUDE_ROOT)) for p in surface if INCLUDE_ROOT in p.parents
    }
    violations: list[str] = []
    for root in PLUGIN_SOURCE_ROOTS:
        base = REPO_ROOT / root
        if not base.is_dir():
            continue
        for src in sorted(base.rglob("*.cpp")):
            if any(part.startswith("build") for part in src.parts):
                continue
            text = read_text(src)
            if not PLUGIN_MARKER_RE.search(text):
                continue
            for line in text.splitlines():
                m = INCLUDE_RE.match(line)
                if not m:
                    continue
                inc = m.group(1)
                if inc in GENERATED_HEADERS or inc in surface_incs:
                    continue
                if is_impl_header(inc):
                    continue
                violations.append(
                    f"{src.relative_to(REPO_ROOT)}: includes '{inc}', which is "
                    "outside the declared plugin-ABI surface. Either use a "
                    "surface header or extend the entry points in "
                    "scripts/gen-plugin-abi-surface.py (a contract change)."
                )
    return violations


def render_manifest(surface: set[Path], options: set[str]) -> str:
    lines = [HEADER_COMMENT, "[headers]"]
    lines.extend(sorted(str(p.relative_to(REPO_ROOT)) for p in surface))
    lines.append("")
    lines.append("[options]")
    lines.extend(sorted(options))
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv[1:]

    surface, errors = compute_closure(collect_entry_files())
    if errors:
        for e in errors:
            print(f"gen-plugin-abi-surface: {e}", file=sys.stderr)
        return 1

    violations = check_plugin_sources(surface)
    if violations:
        for v in violations:
            print(f"gen-plugin-abi-surface: {v}", file=sys.stderr)
        return 1

    rendered = render_manifest(surface, collect_option_tokens(surface))

    if check:
        current = MANIFEST_PATH.read_text() if MANIFEST_PATH.is_file() else ""
        if current != rendered:
            cur_lines = set(current.splitlines())
            new_lines = set(rendered.splitlines())
            for missing in sorted(new_lines - cur_lines):
                print(f"gen-plugin-abi-surface: missing: {missing}", file=sys.stderr)
            for stale in sorted(cur_lines - new_lines):
                print(f"gen-plugin-abi-surface: stale:   {stale}", file=sys.stderr)
            print(
                "gen-plugin-abi-surface: scripts/plugin-abi-surface.txt is out of "
                "date; run scripts/gen-plugin-abi-surface.py and review the diff.",
                file=sys.stderr,
            )
            return 1
        print("gen-plugin-abi-surface: manifest is current.")
        return 0

    MANIFEST_PATH.write_text(rendered)
    n_headers = sum(1 for p in surface)
    print(f"gen-plugin-abi-surface: wrote {MANIFEST_PATH.relative_to(REPO_ROOT)} "
          f"({n_headers} headers)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
