#!/usr/bin/env python3
"""Merge protocol trace files into one ordered NDJSON stream for validation.

    scripts/protocol-trace-merge.py [--job N] [--out merged.ndjson] PATH...

Each PATH is a .ndjson file the engine wrote (CLINK_PROTOCOL_TRACE_DIR) or a
directory of them: one file per process. Events are ordered by their
wall-clock timestamp, then by per-process sequence number; on one machine that
is the causal order, since causally related events from different processes
are separated by a network round trip. Events carrying a `job` field are kept
for one job (--job, else the job of the first Trigger seen, else the first job
seen); events without one (sink-side events know only their subtask) are kept
as they are, so a directory should hold one job's run.

Writes the merged stream and prints a one-line summary. Exit 2 when nothing
was found.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def collect(paths: list[str]) -> list[dict]:
    events: list[dict] = []
    for raw in paths:
        p = Path(raw)
        files = sorted(p.glob("*.ndjson")) if p.is_dir() else [p]
        for f in files:
            with f.open() as fh:
                for n, line in enumerate(fh, 1):
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        e = json.loads(line)
                    except json.JSONDecodeError as ex:
                        raise SystemExit(f"{f}:{n}: not JSON: {ex}") from ex
                    if "event" not in e or "seq" not in e or "ts" not in e:
                        raise SystemExit(f"{f}:{n}: missing event/seq/ts")
                    events.append(e)
    return events


def write_constants(events: list[dict], out: str) -> None:
    """The trace module's constants as literals, derived here once.

    TraceExactlyOnce.tla used to derive them from the trace inside TLC (the
    sink set from the SinkPrepare events, the hosts from the first Placement of
    each sink, the fault budgets from the counts of the fault events, and so
    on). TLC re-evaluates such definitions on every reference, so each step
    walked the whole trace again and validation was quadratic in trace length:
    180 events in 6 seconds, 900 in 120, 1,500 in 300. As literals in a
    generated module the derivations cost nothing at check time. Every
    definition here mirrors the one the module had; the module EXTENDS this
    file, which the validator places on TLC's library path beside the trace.
    """

    def of(kind: str) -> list[dict]:
        return [e for e in events if e["event"] == kind]

    def tla_str(v: str) -> str:
        return '"' + v.replace('"', '\\"') + '"'

    sinks = sorted({e["sub"] for e in of("SinkPrepare")})
    workers = sorted({e["worker"] for e in events
                      if e["event"] in ("Placement", "DeliverBarrier", "WorkerDies")})

    def first_placement(pred) -> str | None:
        for e in events:
            if e["event"] == "Placement" and pred(e):
                return e["worker"]
        return None

    host = {s: first_placement(lambda e, s=s: e.get("sub") == s) for s in sinks}
    src = first_placement(lambda e: e.get("source")) or (workers[0] if workers else "none")
    ckpts = [e["ckpt"] for e in events if "ckpt" in e]
    max_ckpt = max(ckpts) if ckpts else 1
    recoverable = all(e.get("family") == "recoverable" for e in of("SinkPrepare"))
    epochs = [e["epoch"] for e in of("Trigger") + of("DeliverBarrier") if "epoch" in e]
    first_epoch = min(epochs) if epochs else 1
    host_def = (" @@ ".join(f"({s} :> {tla_str(w)})" for s, w in host.items())
                if host else '[s \\in {} |-> "none"]')
    lines = [
        "---- MODULE TraceConstants ----",
        "\\* GENERATED by scripts/protocol-trace-merge.py --constants, from the merged",
        "\\* trace it was written beside: the trace module's constants as literals.",
        "\\* Not tracked; do not edit.",
        "EXTENDS Naturals, TLC",
        f"TraceLen == {len(events)}",
        "TraceSinks == {" + ", ".join(str(s) for s in sinks) + "}",
        "TraceWorkers == {" + ", ".join(tla_str(w) for w in workers) + "}",
        f"TraceHost == {host_def}",
        f"TraceSrcWorker == {tla_str(src)}",
        f"TraceMaxCkpt == {max_ckpt}",
        f"TraceMaxInFlight == {max_ckpt + 1}   \\* the engine does not bound in-flight checkpoints",
        f"TraceRecoverable == {'TRUE' if recoverable else 'FALSE'}",
        f"TraceMaxWorkerDeaths == {len(of('WorkerDies'))}",
        f"TraceMaxCoordDeaths == {len(of('CoordRecovers'))}",
        f"TraceMaxSnapFails == {sum(1 for e in of('SubtaskAck') if not e.get('ok', True))}",
        f"TraceMaxExpiries == {sum(1 for e in of('WalkProbes') if e.get('verdict') == 'refused')}",
        f"TraceMaxBrokerOutages == {len(of('WalkRetries')) + len(of('WalkExhausted'))}",
        f"TraceMaxWalkCancels == {len(of('WalkCancelled'))}",
        f"TraceMaxErrorRestarts == {len(of('RestartOnError'))}",
        f"TraceFirstEpoch == {first_epoch}   \\* the engine's epochs need not start at 1; the model's do",
        "====",
    ]
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("paths", nargs="+")
    ap.add_argument("--job", type=int, default=None, help="keep this job's events (default: the first Trigger's job)")
    ap.add_argument("--constants", default=None,
                    help="also write the trace module's constants, derived from the kept events, as a TLA+ module of literals (TraceConstants.tla)")
    ap.add_argument("--out", default="-", help="output file (default stdout)")
    args = ap.parse_args(argv)

    events = collect(args.paths)
    if not events:
        print("protocol-trace-merge: no events found", file=sys.stderr)
        return 2
    events.sort(key=lambda e: (e["ts"], e.get("proc", ""), e["seq"]))

    job = args.job
    if job is None:
        for e in events:
            if e["event"] == "Trigger" and "job" in e:
                job = e["job"]
                break
    if job is None:
        for e in events:
            if "job" in e:
                job = e["job"]
                break
    kept = [e for e in events if "job" not in e or e["job"] == job]

    out = sys.stdout if args.out == "-" else open(args.out, "w")
    try:
        for e in kept:
            out.write(json.dumps(e, separators=(",", ":")) + "\n")
    finally:
        if out is not sys.stdout:
            out.close()
    kinds: dict[str, int] = {}
    for e in kept:
        kinds[e["event"]] = kinds.get(e["event"], 0) + 1
    if args.constants:
        write_constants(kept, args.constants)
    summary = ", ".join(f"{k}={v}" for k, v in sorted(kinds.items()))
    print(f"protocol-trace-merge: {len(kept)} event(s) for job {job} from {len(events)} read ({summary})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
